server:
  port: 21084
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: test
  rabbitmq:
    host: 172.16.0.66
    port: 5672
    username: admin
    password: admin
    virtual-host: root
    publisher-returns: true
    connection-timeout: 5000
config:
  rabbit:
    queueName: receiveXmlQueue

mqPath:

  msgPersist: D:\mq\msgFile
  received: D:\mq\exchange\04received
  done: D:\mq\exchange\05done
  failed: D:\mq\exchange\06failed
  returnTxt: D:\mq\exchange\07returntxt
  buildxml:
    sendingxml: D:\mq\exchange\01buildxml\sendingxml
