server:
  port: 21080
  tomcat:
    threads:
      max: 20
spring:
  rabbitmq:
    host: 172.16.0.66
    port: 5672
    username: admin
    password: admin
    virtual-host: root
    publisher-returns: true
    connection-timeout: 5000
sysconfig:
  rabbit:
    maxwait: 1000
    backupfolder: D:\mq\file
    filesuffix: .json
    organcode: null
  queue:
    document: null
queuefile: D:\GIT103\scspm\GW2020_Interface\code\exchangeServer\msgReceiveCenter\src\main\resources\QueueConfig.xml